name: ejson2env

type: go

up:
  - go:
      version: 1.18
      modules: true
  - homebrew:
      - golangci-lint

# `dev run` runs `dev build` and then `dev run-built` if these are both defined.
commands:
  build:
    run: go build -o bin/ ./cmd/...
  test:
    run: go test -v -race -cover ./...
  style:
    run: golangci-lint run ./...
